apiVersion: v1
kind: Service

metadata:
  name: {name}-service
  labels:
    app: {label}

spec:
  selector:
    app: {label}
  type: {type}
  clusterIP: 0.0.0.0 # to edit
  ports:
  - port: 3000 # to edit
    targetPort: 3000 # to edit
    nodePort: 30000 # to edit