apiVersion: v1
kind: Service

metadata:
  name: {name}-service
  labels:
    app: {label}

spec:
  selector:
    app: {label}
  type: {type}
  clusterIP:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000